### ISSUE TITLE
💡 [FEATURE] - Create Footer Section

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#12]
**Description:**

The footer section is a crucial part of our project's user interface, providing important links and information. This issue focuses on creating the `Footer.jsx` component in the `components` folder, including appropriate links, copyrights, logos, and a visually appealing design.

**Steps to Contribute:**

1. Create `Footer.jsx`: Develop the `Footer.jsx` component in the `components` folder.
2. Add Links: Include relevant links such as contact, privacy policy, terms of service, and any other important links.
3. Copyright and Logo: Add a copyright notice and our project's logo in the footer.
4. Styling: Apply styles to ensure the footer looks clean and visually appealing.

By contributing to this issue, you'll help provide essential information and navigation options to users of our project.

Your contribution to creating an attractive and informative footer is highly valued! Let's make our project's footer both functional and aesthetically pleasing.

**Comment by JairTorres1003** [comment]
Hello @Pinaka-Pani-18 
I would like to contribute to this topic.
Can you assign it to me?

**Comment by Pinaka-Pani-18** [comment]
> Hello @Pinaka-Pani-18 I would like to contribute to this topic. Can you assign it to me?

Hi @JairTorres1003, I have assigned it to you. Please don't create a PR without assigning it to yourself. Please also close the previous PR and create a new PR with styling using Tailwind CSS

**Comment by JairTorres1003** [comment]
okay, I got it

**Comment by JairTorres1003** [comment]
Ready @Pinaka-Pani-18 , corrected and applied what you told me and to enable Tailwind CSS, add the necessary dependencies, including tailwindcss, postcss, and autoprefixer.

**Comment by Pinaka-Pani-18** [comment]
Hi @JairTorres1003 
The footer Looks good. Thank you for your contribution.
