### ISSUE TITLE
💡 [FEATURE] - Create Contributors Section 

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#14]
**Description:**

The contributors section is an important part of our project, recognizing and listing all the contributors who have made valuable contributions. This issue focuses on creating the `Contributors.jsx` component in the `components` folder, which will list all the contributors and provide a link to their GitHub profiles.

**Steps to Contribute:**

1. **Create `Contributors.jsx`:** Develop the `Contributors.jsx` component in the `components` folder.
2. **Display Contributors:** Implement functionality to list and display all contributors to our project.
3. **GitHub Profile Links:** Enhance the contributors' listing by adding links to their respective GitHub profiles, making it easy for users to explore their profiles and contributions.
4. **Styling:** Apply styles to make the contributors section visually appealing and organized.

By contributing to this issue, you'll help acknowledge and highlight the valuable contributions of all contributors to our project and provide users with easy access to their GitHub profiles.

Your contribution in creating the contributors section with GitHub profile links is greatly valued! Let's recognize and appreciate our community of contributors while enhancing their visibility.

**Comment by Thejas0604** [comment]
Can you specify the requirement please ?

**Comment by Pinaka-Pani-18** [comment]
> Can you specify the requirement please ?

Hello @Thejas0604,

The specifications for the Contributors.jsx file should include displaying contributors with their profile logos and linking to their GitHub profiles. Additionally, the page should be responsive.

For now, please create dummy data for our contributors and display it on the page by mapping through the data. The contributors' data is available on the right of the repository.

In the future, or if it becomes possible, I would like the contributors' data to be updated dynamically as they contribute to our project, automatically adding them to the list.

**Comment by Thejas0604** [comment]
Dear @Pinaka-Pani-18 ,

So just to make sure I am a complete beginner for this open source as well as `.jsx` I'll try my best to contribute. I think I have to create a `contributors.jsx` component and style it using a `.css` file right?

**Comment by mohiwalla** [comment]
Hi @Pinaka-Pani-18, Please assign this issue to me.

**Comment by mohiwalla** [comment]
And one more thing @Pinaka-Pani-18 to highlight, during **development**, I found that their is an **rate limit** for an _IP Address_ on `GitHub API`. So how about if in new PR I add some **cache mechanism** to store the fetched results in `localStorage` for almost **_2 hours_** so that the user doesn't run out of `credits`?

**Comment by Pinaka-Pani-18** [comment]
> And one more thing @Pinaka-Pani-18 to highlight, during **development**, I found that their is an **rate limit** for an _IP Address_ on `GitHub API`. So how about if in new PR I add some **cache mechanism** to store the fetched results in `localStorage` for almost **_2 hours_** so that the user doesn't run out of `credits`?

Hi @mohiwalla, sure, go ahead with it, but if possible, could you style this using Tailwind CSS?

**Comment by Pinaka-Pani-18** [comment]
Hi @mohiwalla, any update ?

**Comment by mohiwalla** [comment]
Yes the code is ready, I'll push within an hour after reaching home 😅

**Comment by mohiwalla** [comment]
Hi @Pinaka-Pani-18, just pushed all discussed changes. Please review do we need to change anything else?

**Comment by Pinaka-Pani-18** [comment]
> Hi @Pinaka-Pani-18, just pushed all discussed changes. Please review do we need to change anything else?

Everything is fine, but there is a mismatch in the background color. Please fix it.
