### ISSUE TITLE
💡 [FEATURE] - Create Discord Channel and Add Appropriate Links in Doc

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#2]
**Description:**

The project currently lacks a dedicated Discord channel for community discussions and interactions. To foster collaboration and engagement among our users and contributors, we need to create an official Discord channel.

**Steps to Contribute:**

1. **Create Discord Channel:** If you have experience setting up Discord servers and channels, please create an official channel for our project. Ensure it's well-organized and includes relevant categories for discussions, announcements, and support.

2. **Update Documentation:** After creating the Discord channel, update the project's documentation, including the README file, by adding a direct link to the newly created Discord channel. Replace any placeholders (e.g., "url-to-chat-rooms") with the actual URL to the Discord channel.

3. **Verify Access:** Make sure that the Discord channel is accessible to the project's community, and consider setting up appropriate roles and permissions for moderators and contributors.

By contributing to this issue, you'll help establish a valuable communication platform for our project, making it easier for community members to connect, share ideas, and seek assistance.

Your efforts are highly appreciated in strengthening our project's community! Let's create an inviting and collaborative space on Discord.

**Comment by KaneshiroKeola** [comment]
Hello, 

I can help set up the discord channel roles/self roles, and different categories and chats as well as add bots to the channel and add voice chats if needed. To keep things organized.

I am not super sure about the Documentation part but anything you need me to do in discord i will do my best work to make it look clean and organized.

**Comment by Pinaka-Pani-18** [comment]
> Hello,
> 
> I can help set up the discord channel roles/self roles, and different categories and chats as well as add bots to the channel and add voice chats if needed. To keep things organized.
> 
> I am not super sure about the Documentation part but anything you need me to do in discord i will do my best work to make it look clean and organized.

Great! I am assigning this task to you. Please start working on it.

**Comment by KaneshiroKeola** [comment]
I Have completed creating the discord server adding appropriate roles, categories, and channels :)

https://discord.gg/YgUySdJC

I may need to assign you the owner role once you join so that you are able to make any extra necessary changes but other than that the server is completed.
I have also uploaded the server link in the README.md.

**Comment by Pinaka-Pani-18** [comment]
> I Have completed creating the discord server adding appropriate roles, categories, and channels :)
> 
> https://discord.gg/YgUySdJC
> 
> I may need to assign you the owner role once you join so that you are able to make any extra necessary changes but other than that the server is completed. I have also uploaded the server link in the README.md.

Great work, @KaneshiroKeola ! 
You've done a fantastic job, and the server looks great. 

I have joined the server, and you can assign me the owner role.

Thank you for your contribution!
