### ISSUE TITLE
🐛 [BUG] - Github workflow for greetings is not working

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#28]
### Description:
I have already created a GitHub workflow for greetings, but it is not working as expected, and it's not greeting the contributors.

### Tasks:
- [ ] Resolve the issue without modifying the greeting messages.

**Comment by WallysFerreira** [comment]
Hey I would like to try to fix this

**Comment by Pinaka-Pani-18** [comment]
> Hey I would like to try to fix this

Assigned to you @WallysFerreira , you can start fixing this bug.
