### ISSUE TITLE
💡 [FEATURE] - Raise Your Own Issues and Work for It

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#33]
## Description

As our project, Hacktoberfest Projects Hub, is a newly created project, we are welcoming newly created issues.

## Tasks
- [ ]   Create an issue that adds value to our project and enhances your knowledge or skills.

Note: The project maintainer will review the issue, and upon approval, you can start working on it.

**Comment by Aditya9764** [comment]
@Pinaka-Pani-18  ok I'm adding header  can you please accep my contribution as hacktoberfest accepted mark
