### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Aditya9764** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#37]
**Is your feature request related to a problem? Please describe.**

**Describe the Solution You'd Like**

**Describe Alternatives You've Considered**

**Additional Context**

**Labels**

Please add appropriate labels to this issue: `enhancement`, `feature-request`, etc.

**Comment by Aditya9764** [comment]
please mark it as Hacktoberfest so that I can contribute to Hacktoberfest

**Comment by Pinaka-Pani-18** [comment]
Hi @Aditya9764 , the header is already available in the project.

**Comment by Pinaka-Pani-18** [comment]
> please mark it as Hacktoberfest so that I can contribute to Hacktoberfest 

No need to raise this issue because the header is already in place. Please create another issue that can enhance the project's UI and contribute to your skill improvement

**Comment by Aditya9764** [comment]
@Pinaka-Pani-18 OK i will improve the home UI and Contributor page UI with CSS and Bootstrap

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 OK i will improve the home UI and Contributor page UI with CSS and Bootstrap

Use tailwindCSS to enhance the pages

**Comment by Aditya9764** [comment]
ok sure, please accept my issue

**Comment by Aditya9764** [comment]
Which Type of Project you are looking for so that I sill also contribute in adding project link on project page
