### ISSUE TITLE
🐛 [BUG] - workflow for greeting new contributors

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#40]
### Description

The workflow is not functioning correctly when a new contributor raises their first issue or PR.

This is how it is being displayed:
![Screenshot 2023-10-14 102153](https://github.com/Pinaka-Pani-18/Hacktoberfest-Projects-Hub/assets/102857774/bab37398-ea4a-431d-90f5-4ba48cbe12e2)

**Tasks:**
- [ ] Examine the workflow configuration and identify the root cause of the problem. Make necessary adjustments to ensure it works as expected.

**Comment by JulianToppo** [comment]
I would like to work on this issue .
