### ISSUE TITLE
✨ [ENHANCEMENT] - Improve Navbar Responsiveness

### ISSUE THREAD

**Issue by hanzalahwaheed** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#45]
**Describe the Enhancement**

The navbar can be improved when viewing it in mobile devices. The hamburger menu icon and the title should not collapse.

**Current Behavior**

![image](https://github.com/Pinaka-Pani-18/Hacktoberfest-Projects-Hub/assets/101456741/45c7282c-a339-4804-8444-6951f478e6aa)
**Desired Behavior**

We can improve the responsiveness of the website via code.

**Labels**

`enhancement`, `feature-request`

**Comment by hanzalahwaheed** [comment]
@Pinaka-Pani-18  Can I please be assigned to it for Hacktoberfest?

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 Can I please be assigned to it for Hacktoberfest?

Hello @hanzalahwaheed  , this repo has been excluded from Hacktoberfest, but I'm not sure of the reason. I suspect it might have been reported. As a result, I have created the same project [here](https://github.com/Pinaka-Pani-18/Public-Codebases). You can create an issue there, and you can comment on it and make the necessary changes. Afterward, you can create a PR.
