### ISSUE TITLE
📄 [DOCS] - Enhance CONTRIBUTING.md with Images

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#6]
**Issue: Enhance CONTRIBUTING.md with Images**

**Description:**

The CONTRIBUTING.md file is a vital resource for guiding contributors on how to get involved in our project. To improve the clarity and understanding of the contribution process, this issue focuses on enhancing CONTRIBUTING.md by adding appropriate images that complement the text and make it more user-friendly.

**Steps to Contribute:**

1. **Select Relevant Images:** Identify key sections in the CONTRIBUTING.md file where images would be beneficial in explaining the contribution process or specific steps. Choose images that provide a clear visual representation of the content.

2. **Add Images to CONTRIBUTING.md:** Update the CONTRIBUTING.md file by incorporating these selected images into their respective sections. Ensure that the images are appropriately placed, formatted, and aligned with the text for a cleaner and more intuitive understanding.

3. **Review and Feedback:** Collaborate with other contributors to review the changes and gather feedback on the effectiveness of the added images. Make any necessary adjustments based on the feedback received.

4. **Testing:** After adding images, test the CONTRIBUTING.md file to ensure that the images display correctly in various Markdown renderers and platforms.

5. **Additional Rules:** As part of this enhancement, we will also add the following rules to the CONTRIBUTING.md file:
   - Before working on a contribution, please ensure to comment in the respective issue to express your interest and get confirmation from the maintainers. This helps avoid duplicated efforts and ensures that your contribution aligns with the project's goals.
   - Do not start working on an issue or make a pull request (PR) until it has been assigned to you by the maintainers. Contributions that are not assigned in advance may be rejected.

By contributing to this issue, you'll help enhance the CONTRIBUTING.md file by making it more visually informative and easier to follow. Clear and relevant images can significantly improve contributors' understanding of our project's contribution guidelines.

Your efforts in improving the clarity of our contribution documentation are highly valued. Let's enhance the CONTRIBUTING.md file with well-placed and informative images!

**Comment by mohiwalla** [comment]
Hi @Pinaka-Pani-18, Can you please assign this issue to me? I'd complete it before `02:30`, if you assign it to me before `01:30`.

**Comment by Pinaka-Pani-18** [comment]
> Hi @Pinaka-Pani-18, Can you please assign this issue to me? I'd complete it before `02:30`, if you assign it to me before `01:30`.

I have assigned this issue to you. You can start working on it.
