### ISSUE TITLE
💡 [FEATURE] - Add MIT License to the Project

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Hacktoberfest-Projects-Hub#8]
**Description:**

Open source projects thrive on transparency, collaboration, and clear licensing. To ensure that our project is openly accessible to contributors and users while protecting its rights, this issue is dedicated to adding the MIT License to our project.

**Steps to Contribute:**

1. **License Selection:** Collaborate with the team to confirm the selection of the MIT License for our project. The MIT License is known for its permissiveness and is widely used in the open source community.

2. **License File Creation:** Create a new file named `LICENSE` (all in uppercase) in the project's root directory. Copy and paste the full text of the MIT License into this file. The license text can be found on the official MIT License website.

3. **Updating README:** After adding the license file, ensure that the README.md file is updated to include information about the project's licensing. Add a section specifying that the project is licensed under the MIT License and provide a link to the `LICENSE` file.

4. **Testing:** Verify that the license file is correctly formatted and that it displays the MIT License in its entirety.

By contributing to this issue, you'll help ensure that our project is properly licensed and complies with open source best practices. The MIT License allows for wide collaboration while providing clarity on the terms of use.

Your efforts in adding the MIT License to our project are greatly appreciated! Let's make our project even more accessible and transparent.

**Comment by itspunkaj** [comment]
I would like to contribute to this issue
